### ISSUE TITLE
OSM Plugin help for ST3

### ISSUE THREAD

**Issue by tsofron** [gerhardol/gps-running#29]
Hello Gerhardol - first - thanks for all your plugins! It was a good time for Sporttracks :(. One thing i would kindly ask you - by any chance, do you have an opensourcemap plugin that works and could share it with me? :D...Thanks a lot, Tudor (tsofron@hotmail.com).
PS: You can definitely close the 'issue' :D, but i thought this way you'll get a notification

**Comment by gerhardol** [comment]
https://github.com/gerhardol/sporttracks-nordic-mapproviders has support for some mostly Swedish mapproviders
apply-routes have an online component that is mostly not working as well as an offline possibility (there were an instruction in the ST forums that of course is lost now)

Still using ST myself
